import Head from 'next/head'
import Gift from '../components/Gift';
import Hero from '../components/Hero';
import Parallex from '../components/Parallex';
import Shop from '../components/Shop';
import Swiper from '../components/Swiper';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Parallex />
        <Gift />
        <Shop />
        <Swiper />
      </main>
    </>
  )
}
